 name: OWNet
 abstract: Build and install OWNet module
 version: 1.11
 author:
   - Paul H Alfille <palfille@earthlink.net>
 license: perl
 distribution_type: module
 requires:
   IO::Socket::INET: 0
   perl: 5.005_03
 recommends:
   Net::Rendezvous: 0
 build_requires:
   Test: 0
 urls:
   license: http://dev.perl.org/licenses/
 meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
 generated_by: Module::Build version 0.20
